server:
  port: 8080
#spring:
#  profiles:
#    active: prod
#---
#server:
#  port: 8082
#spring:
#  prefiles: dev
#---
#server:
#  port: 8081
#spring:
#  prefiles: prod
#---




person:
  lastName: zhanzan
  age: 18
  boss: alse
  birth: 2019/2/28
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗
    age: 2

